apiVersion: webapp.my.domain/v1alpha1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: z-operator
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
